name: bambu-qsar
channels:
  - anaconda
  - bioconda
  - rdkit
  - mordred
  - conda-forge
dependencies:
  - python=3.8
  - jupyter
  - pip
  - rdkit
  - cmake
  - mordred
  - pip:
     - git+https://github.com/samoturk/mol2vec
     - -r requirements.txt
     - twine
     - -e .
